version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti1906_nonadmin_GithubProject
  gitServerName: srcCtrl_nonadmin_Github_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
