version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti1906_nonadmin_GithubProject
  gitServerName: srcCtrl_nonadmin_Github_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  version: "1.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
- name: substractpackage
  gitServerName: RAHS_GL_IBM_Account_SD
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: rahul-singh-IBM-68
  gitBranch: master
services:
- serviceName: project.serengeti1906_nonadmin_github.integrations:nonadminfs
  packages:
  - name: Serengeti1906_nonadmin_GithubProject
    version: "1.0"
  - name: upperfspackage
    version: "1.0"
- serviceName: UpperFSPackage:upperfs
  packages:
  - name: upperfspackage
    version: "1.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
